% --------------------------------------------------------------
% Dipole Antenna Analysis Script
% Generated by MATLAB(R) Antenna Toolbox
% Frequency: 145 MHz (VHF Band)
% --------------------------------------------------------------

clc; clear; close all;

%% --- 1. Design the Dipole Antenna ---
freqCenter = 145e6;            % Operating frequency (Hz)
antennaObject = design(dipole, freqCenter)

% Visualize antenna structure
figure;
show(antennaObject)
title('3D View of 145 MHz Half-Wave Dipole Antenna');

%% --- Frequency Setup ---
freqRange = (130.5:1.2:159.5)*1e6;
refImpedance = 50;
plotFrequency = freqCenter;

%% --- 2. Impedance vs Frequency ---
figure;
impedance(antennaObject, freqRange);
title('Input Impedance vs Frequency');
grid on;

%% --- 3. S-Parameters (Return Loss) ---
s = sparameters(antennaObject, freqRange, refImpedance);
figure;
rfplot(s);
title('S11 (Return Loss) vs Frequency');
grid on;

%% --- 4. VSWR vs Frequency ---
% VSWR = (1 + |Γ|) / (1 - |Γ|), where |Γ| = |S11|
S11 = rfparam(s,1,1);
GammaMag = abs(S11);
VSWR = (1 + GammaMag) ./ (1 - GammaMag);

figure;
plot(freqRange/1e6, VSWR, 'LineWidth', 1.8);
xlabel('Frequency (MHz)');
ylabel('VSWR');
title('VSWR vs Frequency');
grid on;
ylim([1 5]);
yline(2,'r--','VSWR=2 (Typical Limit)');
yline(1.5,'g--','VSWR=1.5 (Good Match)');

%% --- 5. 3D Radiation Pattern at 145 MHz ---
figure;
pattern(antennaObject, plotFrequency);
title('3D Radiation Pattern at 145 MHz');

%% --- 6. 2D Elevation Pattern (Vertical Plane) ---
figure;
patternElevation(antennaObject, plotFrequency, 0, 'Elevation', 0:5:360);
title('Elevation Pattern (Vertical) at 145 MHz');

%% --- 7. 2D Azimuth Pattern (Horizontal Plane) ---
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360);
title('Azimuth Pattern (Horizontal) at 145 MHz');

%% --- 8. Gain (or Directivity) vs Frequency ---
gain_dBi = zeros(size(freqRange));   % Preallocate array

for i = 1:length(freqRange)
    gain_dBi(i) = pattern(antennaObject, freqRange(i), 0, 0, 'Type', 'directivity');
end

figure;
plot(freqRange/1e6, gain_dBi, 'LineWidth', 1.8);
xlabel('Frequency (MHz)');
ylabel('Directivity (dBi)');
title('Gain (Directivity) vs Frequency');
grid on;
